# fly.toml app configuration file generated for open-mt-api on 2023-06-25T15:17:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "open-mt-api" # TODO Move to staging by default
primary_region = "cdg"

[build]
  builder = "heroku/buildpacks:20"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
